export const REQUEST_ANIMALS = 'REQUEST_ANIMALS'
export const GET_ANIMALS_FAILURE = 'GET_ANIMALS_FAILURE'
export const GET_ANIMALS_SUCCESS = 'GET_ANIMALS_SUCCESS'
export const SELECT_ANIMAL = 'SELECT_ANIMAL';
export const RESET_ANIMAL = 'RESET_ANIMAL';